### PR TITLE
Bump Plugin Utilities API from 2.14.0 to 2.16.0

### PR DESCRIPTION
**Pull request by basil**
Adapting to https://github.com/jenkinsci/plugin-util-api-plugin/pull/161. The motivation for this is getting `jenkinsci/bom` up and running with JENKINS-45047, which exposes this compatibility problem.

Monkey see, monkey do style programming (copying `warnings-ng`), so please don't be too hard on me. I have no idea what I am doing here, just banging around on a keyboard until the tests pass. If something doesn't make sense to you, there is probably a better way. One thing I am confident about is that each and every change in this PR is necessary to get the tests to pass, so if you think some change isn't necessary, try testing without it and see what happens.

CC @timja @uhafner

### CODE REVIEW

**Comment by basil** [comment]
Please hold as I fix the style checks that were reported to me when doing a CI build but not reported to me in a local build. =\

**Comment by basil** [comment]
Checkstyle now complains about redundant `public` modifiers on lines 164 and 175 of `WithChecksStepITest`, but I couldn't figure out how to remove the `public` modifiers without breaking either compilation or `@TestExtension`. I ran into a similar problem in core and ended up suppressing the violations in cases like this. Could the maintainers please suppress these warnings? Thanks!

**Comment by timja** [comment]
FWIW I’ve hit this before :( https://github.com/jenkinsci/checks-api-plugin/issues/99

**Comment by basil** [comment]
The build is now green.

**Review by timja — APPROVED** [review]

**Pull request merged**
