### PR TITLE
Remove beta restrictions

### PR DESCRIPTION
**Pull request by XiongKezhi**

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
+1

**Comment by timja** [comment]
Looks like you need to adjust rev-api config or bump a semver version.

**Comment by XiongKezhi** [comment]
> Looks like you need to adjust rev-api config or bump a semver version.

Yes, I'll adjust the config, or we'll have to update to 2.0.0 which I think is bad since we haven't done many things.

**Comment by timja** [comment]
> > Looks like you need to adjust rev-api config or bump a semver version.
> 
> Yes, I'll adjust the config, or we'll have to update to 2.0.0 which I think is bad since we haven't done many things.

not worth imo just do the config 😄

**Review by uhafner — APPROVED** [review]
Here is an example for some exclusions:
https://github.com/jenkinsci/warnings-ng-plugin/blob/master/plugin/pom.xml#L596

Typically, removing or adding annotations (at least those) does not harm

**Pull request merged**
