### PR TITLE
Ensure we always call getContext().onFailure() in stop

### PR DESCRIPTION
**Pull request by mrginglymus**

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
@mrginglymus have you tested this fixes your issue? or you want to deploy the incremental for a bit?

**Comment by mrginglymus** [comment]
I'll chuck the incremental on and see how it goes. Seems to repro fairly reliably. It'd be nice to test it, but I'm not sure how best to do that.

**Comment by mrginglymus** [comment]
It seems like I need to run a job and abort it externally - do we have a pattern for that?

**Comment by timja** [comment]
> I'll chuck the incremental on and see how it goes. Seems to repro fairly reliably. It'd be nice to test it, but I'm not sure how best to do that.

not needed imo

**Comment by mrginglymus** [comment]
Initial impressions suggest that yes, this has fixed the issue.

**Pull request merged**
