### PR TITLE
Add option to suppress log in job summary

### LINKED ISSUE #92: Feature Request: Option to NOT expose build logs
### Dependencies

N.A.

### Feature Request

The pipeline summary output (https://github.com/jenkinsci/checks-api-plugin/pull/66) is really a NEAT feature, thanks a lot for implementing it!

However in certain cases, it would be interesting to not expose the build's log output.

I'm thinking of the use case of a public code, but with the build output exposing sensitive information even it should not: if the build fails, then the sensitive data is exposed out of Jenkins.
Example which happened with Terraform: [a bug in the `0.13.1` version](https://github.com/hashicorp/terraform/issues/26185) was outputing sensitive data, which could have been exposed on the public repo.

The idea of this feature request can be splitted in 2 axes:

- Add an option to NOT add the build output in the summary (only the stage names, timing and statuses for instance)
- And/Or add an option to disable the pipeline summary when a GitHub MultiBranch / Organization job is used, to keep the benefit of the Check API  without exposing sensitive information

Is this description clear or do you need more information/details?
If it is, does it seem legit?

### PR DESCRIPTION
**Pull request by mrginglymus**
Fixes #92 

I ummed and ahhed a bit over whether to have `suppressLogs` vs `includeLogs` but I went with `true` == override default behaviour (with the assumption that most people _do_ want logs).

### CODE REVIEW

**Review by timja — APPROVED** [review]
looks right

**Comment by mrginglymus** [comment]
There's a leak in our `ChecksProperties`.

**Review by XiongKezhi — APPROVED** [review]
LGTM except for the test failures and pmd warnings.

**Comment by mrginglymus** [comment]
Not sure on those test failures given it works on my machine and Jenkins test infra; I think GitHub got confused by the ninja force push.

**Comment by XiongKezhi** [comment]
> Not sure on those test failures given it works on my machine and Jenkins test infra; I think GitHub got confused by the ninja force push.

Passed on my local machine, but still failed in java 11 build after merging this. Maybe it's a java 11 build problem, I'll test it out.

**Pull request merged**
